# Generated by Django 4.2 on 2023-04-29 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0001_initial'),
        ('games', '0003_game_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='dev',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='devs.dev'),
            preserve_default=False,
        ),
    ]
